### ISSUE TITLE
Size very big

### ISSUE THREAD

**Issue by userbq201** [twolfson/gif-encoder#12] opened 2017-12-26 15:30 UTC
I have 10 images. Each imag size = +-5kb. Summary this 50 kb, but my gif have 500rb. What to do ? I set quality = 20

**Comment by twolfson** [comment] 2017-12-26 18:55
This is a duplicate of https://github.com/twolfson/gif-encoder/issues/8. Please see it for an explanation as well as suggestions for optimizations

**Closed by twolfson** 2017-12-26 18:55 UTC
